// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Ucwngg3a4KxYIonxS8W6kZ3SjqTk5hI',
    appId: '1:696613839776:web:83bd00c44da760563afac5',
    messagingSenderId: '696613839776',
    projectId: 'auth-3ddeb',
    authDomain: 'auth-3ddeb.firebaseapp.com',
    storageBucket: 'auth-3ddeb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA5hcxko7hhjruo003OUMHlxZ8ed_c7jI',
    appId: '1:696613839776:android:d0a8afd2be4ecc1f3afac5',
    messagingSenderId: '696613839776',
    projectId: 'auth-3ddeb',
    storageBucket: 'auth-3ddeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEIoyxjet0_B1a0U_wmgWMA_neXntUgyg',
    appId: '1:696613839776:ios:4bca6dd3bd2d126a3afac5',
    messagingSenderId: '696613839776',
    projectId: 'auth-3ddeb',
    storageBucket: 'auth-3ddeb.firebasestorage.app',
    iosBundleId: 'com.example.studyPlannerProApp',
  );
}
